# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
      - releases/*
      - main
  paths:
    include:
    - percept-testdrive
    - percept-testdrive/pipelines/build-ARMTemplate.yml
    - percept-testdrive/pipelines/deploy-ARMTemplate.yml

pool:
  default

variables:
  ${{ if or(startsWith(variables['Build.SourceBranchName'], 'release'), eq(variables['Build.SourceBranchName'], 'main')) }}:
    Variable_Group: 'ARMTemplate_ReleaseEnvironment'
  ${{ if and(not(startsWith(variables['Build.SourceBranchName'], 'release')), ne(variables['Build.SourceBranchName'], 'main')) }}:
     Variable_Group: 'ARMTemplate_TestEnvironment'


stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    variables:
     - group: ${{variables.Variable_Group}}
    displayName: 'Build ARM Template'
    steps:
    - checkout: self

    - task: Bash@3
      displayName: 'ShellCheck validation for arm template deployment scripts'
      inputs:
        targetType: 'inline'
        script: |
          
          IS_SHELLCHECK_INSTALLED=$(apt list --installed | grep -c -w shellcheck)
          if [ "$IS_SHELLCHECK_INSTALLED" -eq 0 ]; then
              echo "Installing shellcheck"
              sudo apt-get install shellcheck
              echo "Installed shellcheck"
          fi
          
          # Change directory location to template scripts folder
          cd percept-testdrive/deployment/scripts
          
          # Run shellcheck, Shellcheck will return a list of warnings if the script is not compliant with all the rules
          # We are checking the result returned by shellcheck.
          SHELL_CHECK_RESULT_DEPLOY_MODULES=$(shellcheck ./deploy-modules.sh -x)
          if [ -z "$SHELL_CHECK_RESULT_DEPLOY_MODULES" ]; then
            echo "Pass: There are no warnings from shellcheck"
          else
            echo "The following are the warnings for deploy modules script"
            echo "$SHELL_CHECK_RESULT_DEPLOY_MODULES"
            exit 1
          fi

          SHELL_CHECK_RESULT_DEPLOY_MODULES=$(shellcheck ./generate-token.sh -x)
          if [ -z "$SHELL_CHECK_RESULT_DEPLOY_MODULES" ]; then
            echo "Pass: There are no warnings from shellcheck"
          else
            echo "The following are the warnings for deploy modules script"
            echo "$SHELL_CHECK_RESULT_DEPLOY_MODULES"
            exit 1
          fi

          SHELL_CHECK_RESULT_DEPLOY_MODULES=$(shellcheck ./iot-edge-setup.sh -x)
          if [ -z "$SHELL_CHECK_RESULT_DEPLOY_MODULES" ]; then
            echo "Pass: There are no warnings from shellcheck"
          else
            echo "The following are the warnings for deploy modules script"
            echo "$SHELL_CHECK_RESULT_DEPLOY_MODULES"
            exit 1
          fi

          SHELL_CHECK_RESULT_DEPLOY_MODULES=$(shellcheck ./mariner-vm-init.sh -x)
          if [ -z "$SHELL_CHECK_RESULT_DEPLOY_MODULES" ]; then
            echo "Pass: There are no warnings from shellcheck"
          else
            echo "The following are the warnings for deploy modules script"
            echo "$SHELL_CHECK_RESULT_DEPLOY_MODULES"
            exit 1
          fi
          SHELL_CHECK_RESULT_DEPLOY_MODULES=$(shellcheck ./disk-setup.sh -x)
          if [ -z "$SHELL_CHECK_RESULT_DEPLOY_MODULES" ]; then
            echo "Pass: There are no warnings from shellcheck"
          else
            echo "The following are the warnings for deploy modules script"
            echo "$SHELL_CHECK_RESULT_DEPLOY_MODULES"
            exit 1
          fi
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      
    - task: DownloadPipelineArtifact@2
      enabled: true
      displayName: 'Download artifacts from WebApp Build Pipeline'
      inputs:
        buildType: 'specific'
        project: 'ce7d4f25-7269-4f94-a4b8-c7ddb4991e5b'
        definition: '21'
        buildVersionToDownload: 'latest'
        artifactName: 'aptd_app'
        targetPath: '$(System.DefaultWorkingDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy deployment manifest files to a combined folder'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/percept-testdrive/'
        Contents: |
          deployment/arm-templates/*.json
          deployment/scripts/*
          edge-solution/ava-graph/pipelines/person-count-pipeline.json
          edge-solution/ava-graph/topologies/person-count-operation-topology.json
          edge-solution/deployment/manifest/deployment.ava_spatialAnalysis.json
        TargetFolder: '$(System.DefaultWorkingDirectory)/percept-testdrive/combined'
        flattenFolders: true
    
    # Creating the manifest bundle zip from combined folder
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/percept-testdrive/combined'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(System.DefaultWorkingDirectory)/manifest-bundle-azurepercept.zip'
        replaceExistingArchive: true

    - task: CopyFiles@2
      displayName: 'Copy deployment manifest files to a combined folder'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          manifest-bundle-azurepercept.zip
          percept-testdrive-app.zip          
        TargetFolder: '$(System.DefaultWorkingDirectory)/arm_template_bundle_percept'
        flattenFolders: true

    # Creating the ARM Template deployment bundle zip.
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/arm_template_bundle_percept'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/arm-deployment-bundle-percept.zip'
        replaceExistingArchive: true


    # Publishing the pipeline artifact
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/arm-deployment-bundle-percept.zip'
        artifact: 'arm-deployment-bundle-percept'
        publishLocation: 'pipeline'